### ISSUE TITLE
TypeScript compilation errors with global declarations

### ISSUE THREAD

**Issue by fwouts** [cspotcode/cloudformation-typescript-declarations#1]
Thanks for setting this up, it's quite helpful when working with CloudFormation.

I noticed a compilation issue:
```
ERROR in /Users/work/GitHub/deploy-cli/node_modules/cloudformation-declarations/src/declarations/core.ts
[tsl] ERROR in /Users/work/GitHub/deploy-cli/node_modules/cloudformation-declarations/src/declarations/core.ts(54,30)
      TS2312: An interface may only extend a class or another interface.

ERROR in /Users/work/GitHub/deploy-cli/node_modules/cloudformation-declarations/src/declarations/core.ts
[tsl] ERROR in /Users/work/GitHub/deploy-cli/node_modules/cloudformation-declarations/src/declarations/core.ts(55,30)
      TS2312: An interface may only extend a class or another interface.

ERROR in /Users/work/GitHub/deploy-cli/node_modules/cloudformation-declarations/src/declarations/core.ts
[tsl] ERROR in /Users/work/GitHub/deploy-cli/node_modules/cloudformation-declarations/src/declarations/core.ts(56,32)
      TS2312: An interface may only extend a class or another interface.
```

It seems to be caused by the following code:
```
// Brand native types so that they match our Value<> interface.
declare global {
    interface String extends Value<string> {}
    interface Number extends Value<number> {}
    interface Array<T> extends Value<Array<T>> {}
}
```

Removing the code above makes it all work. Is it actually necessary? :)

**Comment by cspotcode** [comment]
Thanks, you're right.  I've published a new version with that code removed, but with this project being in early stages and WIP, I didn't test it.  So let me know if I broke anything.  If you have a moment, I'd also like your opinion.

That code is related to something I've been struggling with: how do we allow Cloudformation's "Fn::" and "Ref" constructs?  If an interface expects a string, but instead we give it a `{'Fn::ImportValue': 'other-value'}`, how do we tell TypeScript this is ok because we're importing a string?

The current solution uses branding and factory functions.  Factories such as "Functions.Sub" declare a return type of `{__brandCloudfrontValue: string}`.  All other interfaces use union types to accept `string | {__brandCloudfrontValue: string}`.  (aka "string or a Cloudformation function that computes a string")  However, this makes compiler errors confusing, since they talk about `__brandCloudfrontValue` instead of a more useful message about missing properties.  When every single value in every single interface might be a `{__brandCloudfrontValue}`, it pollutes documentation popups and code completion.

Alternatively, we can ditch "branding" in favor of a simpler solution: lying to the type system.  In other words, `Functions.Sub()` claims to return a `string` even though it's really returning a `{'Fn::Sub': ...}`.  This is a big caveat, because the type system thinks it's a string, but in reality it's an object.

This caveat should only cause trouble if we're pulling values from our CloudFormation templates.  For example, if I use code completion to write 
```myEc2LaunchConfiguration.Properties.SecurityGroups[0].slice(2)` the type system won't warn me when the security group is actually a `{Ref: ''}` object.  So far, I've never needed to do this.  I build stack templates and convert to JSON.  As far as I'm concerned, they are opaque, atomic values.  How about you?

What do you think?  Sorry for rambling, I hope this makes sense.

**Comment by fwouts** [comment]
Sorry for the late reply—I needed to sit down for a while to understand the issue you were referring to :)

I just read about [nominal typing](https://basarat.gitbooks.io/typescript/docs/tips/nominalTyping.html). Now that I'm familiar with branding, I finally understand the errors I got when I was writing my JSON templates manually. You can see [here](https://github.com/zenclabs/deploy/commit/72c1fc847661a0ed0df3c2286551a01522bc3ecc#diff-8560b4168566a8249665ff16d2398496L107) the `as any` casts I had to add manually because I was using `Ref` (I have now stopped using CloudFormation in my code, for unrelated reasons).

Factory methods would have addressed my issue, if I had known that they were there. Maybe adding [the same comment as the TypeScript team did](https://github.com/Microsoft/TypeScript/blob/7b48a182c05ea4dea81bab73ecbbe9e013a79e99/src/compiler/types.ts#L693-L698) could help when people click through the confusing errors.

I don't like the idea of lying to the type system. It doesn't seem right, and you never know how people will use your code. Even branding seems a little too hacky to me.

In this particular case, I don't think you actually need branding. It's necessary when two structures are compatible and you want to prevent casting one to another. Here however, you know exactly what structures correspond to what type, so you could do this in `functions.ts` and `core.ts`:
```
export interface Base64 {
  'Fn::Base64': StringValue
}

export interface FindInMap {
  'Fn::FindInMap': [StringValue, StringValue, StringValue];
}

...

export interface Ref {
    Ref: string;
}

...

// Instead of using branding, we define each type as an enum of its possible forms.
// Notice that functions such as FindInMap are repeated everywhere, since we don't know
// their return type in advance.

export type StringValue = string | Ref | Base64 | FindInMap | GetAtt | ImportValue | Join | Select | Sub | If;
export type BooleanValue = boolean | Ref | FindInMap | GetAtt | ImportValue | Select | If | And | Equals 
| Not | Or;
...
```

I haven't tried this, and it may be completely wrong, but let me know what you think!

**Comment by cspotcode** [comment]
Thanks for the reply.

I'll add a README section explaining the factory functions, both for resources and for CloudFormation's `Fn::`s.

Initially I agreed with you and used union types.  However, this wreaks havoc with the errors from TS.  Suddenly every single CloudFormation string can actually be a string, or Ref, or Base64, or GetAtt, etc.  And those structures, in turn, can be composed of even more nested "Fn::"s.  It creates an infinite list of recursively nested objects that all compute a string.  (For example, `{"Fn::Base64": {"Fn::Ref": {"Fn::Base64": {/* and so on */}}}}`)  This endless list fills the diagnostic tooltip and makes it really difficult to see what the problem is.  I want to see "number is not assignable to string" but instead I see something like "number is not assignable to <infinite list of possible nested structures here>"

I ended up creating an `Effectively` generic.  The `Base64` factory function returns type `Effectively<string, {"Fn::Base64": string}>`

```typescript
/**
 * When we "lie" to the typesystem, a branding property stores the real type.
 * For example, when we say that a {"Ref": ""} is actually a string,
 * we also brand the return value with an interface.  Something like:
 * 
 *     string & {__cloudfrontIsActually: {Ref: string}}
 * 
 */
export type Effectively<PretendingToBe, IsActually> = PretendingToBe & Actually<IsActually>;
export interface Actually<T> {
    __cloudfrontIsActually: T;
}
```

It's not perfect, but at least it doesn't completely obscure that we're returning inaccurate type information.  0.1.0 includes these changes.
